"""Copies Pokémon image assets referenced by the dashboard payload into the
published site's images/ directory, keyed by pokemon_key so static/app.js
can look them up the same way it looks up every other Pokémon-keyed field.

Two kinds, matching pokemon_asset's two image_kind values:

* `copy_sprites` — Bulbagarden 128x128 menu sprites, copied verbatim to
  images/<pokemon_key>.png. These are the dense-UI asset: correct at
  --icon-sm/--icon-md, where 128px is already more than the box needs.
* `copy_hero_art` — PokéAPI 512x512 HOME renders, downscaled to
  images/hero/<pokemon_key>.webp for the --icon-lg/--icon-xl hero slots
  that visibly blurred when they upscaled a menu sprite. They are
  downscaled rather than copied because shipping 512px source for a
  128px-max box would add tens of megabytes of pixels no CSS box uses.

Image bytes live in gitignored data/assets/ caches (regenerated by
`python -m pipelines.cli extract bulbagarden` and `... extract pokeapi`);
this module never fetches them itself, and degrades gracefully — same
convention as pipelines/dashboard/data.py's mart loading — when a
referenced pokemon_key has no resolvable image: it's skipped, not raised,
so a build with a partial or absent asset cache still succeeds.
"""

from __future__ import annotations

import csv
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_NORMALIZED_DIR = REPO_ROOT / "data" / "normalized"
DEFAULT_ASSET_CACHE_DIR = REPO_ROOT / "data" / "assets" / "bulbagarden"
DEFAULT_ARTWORK_CACHE_DIR = REPO_ROOT / "data" / "assets" / "pokeapi_artwork"

# The largest box hero art is ever drawn into is --icon-xl (128 CSS px), so
# 256 covers a 2x HiDPI display exactly and nothing beyond it. WebP at this
# size lands around 10-15KB per Pokémon against ~130KB for the 512px PNG
# source.
HERO_ART_SIZE_PX = 256


def _read_csv_rows(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open(newline="", encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def load_asset_map(
    normalized_dir: Path = DEFAULT_NORMALIZED_DIR,
    *,
    image_kind: str = "menu_sprite",
) -> dict[str, str]:
    """pokemon_key -> local_cache_path, from data/normalized/pokemon_asset.csv.
    Returns {} gracefully if that file isn't present yet.

    `image_kind` is required in spirit even though it defaults: pokemon_asset
    carries one row per Pokémon *per kind*, so an unfiltered read would
    collapse both kinds onto one key and let whichever row happened to come
    last win — silently pointing menu-sprite lookups at artwork filenames.
    """
    return {
        row["pokemon_key"]: row["local_cache_path"]
        for row in _read_csv_rows(normalized_dir / "pokemon_asset.csv")
        if row.get("local_cache_path") and row.get("image_kind") == image_kind
    }


def copy_sprites(
    pokemon_keys: set[str],
    *,
    output_dir: Path,
    normalized_dir: Path = DEFAULT_NORMALIZED_DIR,
    asset_cache_dir: Path = DEFAULT_ASSET_CACHE_DIR,
) -> dict[str, str]:
    """Copies each resolvable pokemon_key's menu sprite into
    output_dir/images/<pokemon_key>.png and returns a
    {pokemon_key: "images/<pokemon_key>.png"} map of what succeeded.

    Stale sprite files (renamed keys, dropped mart rows) are pruned by name
    at the top level of output_dir/images/ on every call, so they don't
    accumulate across rebuilds. This deliberately only removes *.png files
    directly in images/ rather than rmtree-ing the whole directory
    (backlog.md #47): build.py also populates images/icons/,
    images/reference_teams/ and images/hero/ as sibling subdirectories, and
    an rmtree here would wipe those out too if this function ever ran after
    them instead of before -- a call-order hazard nothing enforced. Pruning
    by name makes this function's own cleanup independent of when it runs
    relative to the others.
    """
    images_dir = output_dir / "images"
    images_dir.mkdir(parents=True, exist_ok=True)
    for stale_sprite in images_dir.glob("*.png"):
        stale_sprite.unlink()

    asset_map = load_asset_map(normalized_dir, image_kind="menu_sprite")
    resolved: dict[str, str] = {}
    for pokemon_key in sorted(pokemon_keys):
        local_cache_path = asset_map.get(pokemon_key)
        if not local_cache_path:
            continue
        source_path = asset_cache_dir / local_cache_path
        if not source_path.exists():
            print(
                f"pipelines.dashboard.sprites: no sprite file at {source_path} "
                f"for pokemon_key={pokemon_key!r}, skipping",
                file=sys.stderr,
            )
            continue
        dest_path = images_dir / f"{pokemon_key}.png"
        shutil.copyfile(source_path, dest_path)
        resolved[pokemon_key] = f"images/{pokemon_key}.png"
    return resolved


def copy_hero_art(
    pokemon_keys: set[str],
    *,
    output_dir: Path,
    normalized_dir: Path = DEFAULT_NORMALIZED_DIR,
    artwork_cache_dir: Path = DEFAULT_ARTWORK_CACHE_DIR,
    size_px: int = HERO_ART_SIZE_PX,
) -> dict[str, str]:
    """Downscales each resolvable pokemon_key's HOME render into
    output_dir/images/hero/<pokemon_key>.webp and returns a
    {pokemon_key: "images/hero/<pokemon_key>.webp"} map of what succeeded.

    Stale files are pruned by name within images/hero/ on every call, the
    same discipline copy_sprites() uses for the top level -- images/hero/ is
    this function's own subdirectory, but pruning by name rather than
    rmtree keeps the two functions' cleanup behaviour identical and
    order-independent.

    Pillow is imported lazily so that a checkout without it (or a build that
    only needs menu sprites) still produces a working dashboard, minus hero
    art -- the same degrade-don't-raise contract as a missing asset cache.
    """
    hero_dir = output_dir / "images" / "hero"
    hero_dir.mkdir(parents=True, exist_ok=True)
    for stale_render in hero_dir.glob("*.webp"):
        stale_render.unlink()

    asset_map = load_asset_map(normalized_dir, image_kind="home_render")
    if not asset_map:
        return {}

    try:
        from PIL import Image
    except ImportError:
        print(
            "pipelines.dashboard.sprites: Pillow is not installed, skipping hero art "
            "(run `make setup`); the dashboard will fall back to menu sprites.",
            file=sys.stderr,
        )
        return {}

    resolved: dict[str, str] = {}
    for pokemon_key in sorted(pokemon_keys):
        local_cache_path = asset_map.get(pokemon_key)
        if not local_cache_path:
            continue
        source_path = artwork_cache_dir / local_cache_path
        if not source_path.exists():
            print(
                f"pipelines.dashboard.sprites: no artwork file at {source_path} "
                f"for pokemon_key={pokemon_key!r}, skipping",
                file=sys.stderr,
            )
            continue
        dest_path = hero_dir / f"{pokemon_key}.webp"
        with Image.open(source_path) as image:
            # RGBA throughout: HOME renders are transparent-background, and
            # the dashboard draws them over both light card surfaces and the
            # dark broadcast header.
            image = image.convert("RGBA")
            image.thumbnail((size_px, size_px), Image.LANCZOS)
            # method=4 rather than Pillow's slowest setting: at this size
            # method=6 roughly triples the per-image encode time for about
            # 2% smaller files, and this runs over ~300 images on every
            # dashboard rebuild.
            image.save(dest_path, "WEBP", quality=88, method=4)
        resolved[pokemon_key] = f"images/hero/{pokemon_key}.webp"
    return resolved
