"""Copies Bulbagarden sprite images referenced by the dashboard payload into
the published site's images/ directory, keyed by pokemon_key so
static/app.js can look them up the same way it looks up every other
Pokémon-keyed field.

Sprite bytes live in the gitignored data/assets/bulbagarden/ cache
(regenerated by `python -m pipelines.cli extract bulbagarden`); this module
never fetches them itself, and degrades gracefully — same convention as
pipelines/dashboard/data.py's mart loading — when a referenced pokemon_key
has no resolvable sprite: it's skipped, not raised, so a build with a
partial or absent sprite cache still succeeds.
"""

from __future__ import annotations

import csv
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_NORMALIZED_DIR = REPO_ROOT / "data" / "normalized"
DEFAULT_ASSET_CACHE_DIR = REPO_ROOT / "data" / "assets" / "bulbagarden"


def _read_csv_rows(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open(newline="", encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def load_asset_map(normalized_dir: Path = DEFAULT_NORMALIZED_DIR) -> dict[str, str]:
    """pokemon_key -> local_cache_path, from data/normalized/pokemon_asset.csv.
    Returns {} gracefully if that file isn't present yet."""
    return {
        row["pokemon_key"]: row["local_cache_path"]
        for row in _read_csv_rows(normalized_dir / "pokemon_asset.csv")
        if row.get("local_cache_path")
    }


def copy_sprites(
    pokemon_keys: set[str],
    *,
    output_dir: Path,
    normalized_dir: Path = DEFAULT_NORMALIZED_DIR,
    asset_cache_dir: Path = DEFAULT_ASSET_CACHE_DIR,
) -> dict[str, str]:
    """Copies each resolvable pokemon_key's sprite into
    output_dir/images/<pokemon_key>.png and returns a
    {pokemon_key: "images/<pokemon_key>.png"} map of what succeeded.

    Stale sprite files (renamed keys, dropped mart rows) are pruned by name
    at the top level of output_dir/images/ on every call, so they don't
    accumulate across rebuilds. This deliberately only removes *.png files
    directly in images/ rather than rmtree-ing the whole directory
    (backlog.md #47): build.py also populates images/icons/ and
    images/reference_teams/ as sibling subdirectories, and an rmtree here
    would wipe those out too if this function ever ran after them instead
    of before -- a call-order hazard nothing enforced. Pruning by name makes
    this function's own cleanup independent of when it runs relative to
    the others.
    """
    images_dir = output_dir / "images"
    images_dir.mkdir(parents=True, exist_ok=True)
    for stale_sprite in images_dir.glob("*.png"):
        stale_sprite.unlink()

    asset_map = load_asset_map(normalized_dir)
    resolved: dict[str, str] = {}
    for pokemon_key in sorted(pokemon_keys):
        local_cache_path = asset_map.get(pokemon_key)
        if not local_cache_path:
            continue
        source_path = asset_cache_dir / local_cache_path
        if not source_path.exists():
            print(
                f"pipelines.dashboard.sprites: no sprite file at {source_path} "
                f"for pokemon_key={pokemon_key!r}, skipping",
                file=sys.stderr,
            )
            continue
        dest_path = images_dir / f"{pokemon_key}.png"
        shutil.copyfile(source_path, dest_path)
        resolved[pokemon_key] = f"images/{pokemon_key}.png"
    return resolved
